name: Bug Report 
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: output-log
    attributes:
      label: Output Log
      description: If applicable, attach your output log file (accepted file types - .txt or .log)
    validations:
      required: false
  - type: dropdown
    id: vr-desktop
    attributes:
      label: Are you in VR or Desktop mode?
      options:
        - VR
        - Desktop
    validations:
      required: true
  - type: dropdown 
    id: linux
    attributes:
      label: Are you on Linux?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
